---
name: Run Ansible Check on CentOS

on: [push, pull_request]

jobs:
  centos-7:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v6

      - run: "sed -i -e 's/ansible.posix.//g' */*.yml */*/*.yml"

      - name: ansible check with centos 7
        uses: roles-ansible/check-ansible-centos-centos7-action@master
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  centos-8:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v6

      - name: ansible check with centos 8
        uses: roles-ansible/check-ansible-centos-centos8-action@master
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  centos-9:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v6

      - name: ansible check with centos 9
        uses: roles-ansible/check-ansible-centos-centos9-action@main
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  centos-10:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v6

      - name: ansible check with centos 10
        uses: roles-ansible/check-ansible-centos-centos10-action@main
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
