name: Run tests on Ubuntu

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  ubuntu-latest:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v6

      - name: ansible check with ubuntu:latest
        uses: roles-ansible/check-ansible-ubuntu-latest-action@master
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  ubuntu-20:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v6

      - name: ansible check with ubuntu:20 (focal)
        uses: roles-ansible/check-ansible-ubuntu-focal-action@master
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
